name: Autograding your code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install --file Main/pom.xml

      - name: Run tests
        id: tests
        run: mvn test --file Main/pom.xml

      - name: Parse test results
        if: ${{ always() }}
        run: |
          mkdir -p test-results
          mv Main/target/surefire-reports/*.xml test-results/
          echo "test_results_file=test-results/*.xml" >> $GITHUB_STATE
          echo $GITHUB_STATE
