name: Java CI with JUnit

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build with Maven
      run: mvn package --quiet

    - name: Run JUnit tests
      run: mvn test --quiet
